[phases.setup]
nixPkgs = ["python313", "pipenv"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium"
]

[start]
cmd = "python main.py"
